version: "3.7"
services:
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883" 
      - "9001:9001" 
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
    restart: unless-stopped
  iot-agent:
    build: ./iot-agent
    container_name: iot-agent
    ports:
      - "8080:8080" 
    restart: unless-stopped
    depends_on: 
      - mqtt5
  api:
    build: ./api
    container_name: api
    ports:
      - "5000:5000" 
    restart: unless-stopped
    environment:
      - PORT=5000
      - MQTT_HOST=mqtt5
      - MQTT_PORT=1883
      - MQTT_USERNAME=admin
      - MQTT_PASSWORD=admin
      - MQTT_CLIENT_ID=iot_api
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin
      - MONGO_DB=iot-dashboard
      - CRATE_HOST=cratedb
      - CRATE_PORT=5432
      - CRATE_USER=crate
    depends_on: 
      - mqtt5
      - iot-agent
      - mongo
      - cratedb  
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017" 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin  
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
  cratedb:
    image: crate:latest
    container_name: crate
    ports:
      - "4200:4200"
      - "5432:5432"
    volumes:
      - crate-data:/tmp/crate/data 
    restart: unless-stopped
volumes:
  config:
  data:
  log:
  mongo-data:
  crate-data:

networks:
  default:
    name: iot-dashboard